import Config

sqlite_defaults = [
  busy_timeout: 5_000,
  journal_mode: :wal
]

# Configure your database
config :dnc_watchdog, DncWatchdog.Repo,
  [
    database: Path.expand("../priv/repo/dnc_watchdog_dev.db", __DIR__),
    pool_size: 10,
    stacktrace: true,
    show_sensitive_data_on_connection_error: true
  ] ++ sqlite_defaults

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
port = String.to_integer(System.get_env("PORT") || "4000")

config :dnc_watchdog, DncWatchdogWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: port],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "nMYeQVyqvKHTVGhvB6mF0gY3v/OyL0ILxi5cYOPQOBmiM1h2Seod7ZYuLzHq6UsC",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:dnc_watchdog, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:dnc_watchdog, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :dnc_watchdog, DncWatchdogWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/dnc_watchdog_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :dnc_watchdog, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

config :dnc_watchdog, :periodic_import,
  enabled: System.get_env("DNC_PERIODIC_IMPORT") == "true",
  lookback_days: String.to_integer(System.get_env("DNC_IMPORT_LOOKBACK_DAYS") || "7"),
  interval_ms: String.to_integer(System.get_env("DNC_IMPORT_INTERVAL_MS") || "900000")

config :dnc_watchdog, :usps_tracking,
  client_id: System.get_env("USPS_CLIENT_ID"),
  client_secret: System.get_env("USPS_CLIENT_SECRET"),
  api_base: System.get_env("USPS_API_BASE") || "https://apis.usps.com"

config :dnc_watchdog, :periodic_tracking_refresh,
  enabled: System.get_env("DNC_PERIODIC_TRACKING_REFRESH") == "true",
  interval_ms: String.to_integer(System.get_env("DNC_TRACKING_REFRESH_INTERVAL_MS") || "3600000"),
  run_on_start: false
