name: CI

on:
  push:
    branches: [main, master]
  pull_request:

env:
  MIX_ENV: test

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.16"
          otp-version: "26"

      - name: Cache deps
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix compile.boundary --warnings-as-errors
      - run: mix compile --warnings-as-errors
      - run: mix format --check-formatted
      - run: mix credo --min-priority high
      - run: mix test
